name: convert

on:
  schedule:
    - cron: '0 14 * * *'

env:
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: cd tool && composer install --prefer-dist --no-progress --no-suggest && cd ..

    - name: Convert
      run: bash ./bin/download_data.sh

    - name: Git add & commit
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "${{ secrets.NAME }}"
        git status | grep "modified:   data/data.json" && git add data/data.json \
          && git commit -m "update data.json: `date +'%Y-%m-%d %H:%M:%S'`"

    - name: Git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_TOKEN }}
        branch: development
